spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/krs_db?currentSchema=krs_schema
spring.datasource.username=krd_postgress
spring.datasource.password=Krs@Prod!Db#2026
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=krs_schema
spring.liquibase.liquibase-schema=krs_schema
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=krs_schema

# --- Logging & Summary ---
app.cors.origins=*
logging.level.liquibase=INFO
logging.level.liquibase.integration.spring.SpringLiquibase=INFO
spring.liquibase.parameters.liquibase.show-summary=SUMMARY

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

server.port=8081
server.address=0.0.0.0

app.messages.error.unauthorized=Session expired or invalid token.

# File Storage Directory Configuration
file.upload-dir=uploads/documents

# Dashboard Time Limit Configuration (max days or overdue)
app.dashboard.max-time-limit-days=120

