spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/krs_db?currentSchema=krs_schema}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:krd_postgress}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Krs@Prod!Db#2026}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=${DB_SCHEMA:krs_schema}
spring.liquibase.liquibase-schema=${DB_SCHEMA:krs_schema}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:krs_schema}

# --- Logging & CORS ---
app.cors.origins=${CORS_ORIGINS:*}
logging.level.liquibase=INFO
logging.level.liquibase.integration.spring.SpringLiquibase=INFO
spring.liquibase.parameters.liquibase.show-summary=SUMMARY

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=${PORT:8081}
server.address=0.0.0.0

app.messages.error.unauthorized=Session expired or invalid token.

# File Storage Directory Configuration
file.upload-dir=${FILE_UPLOAD_DIR:uploads/documents}

# Dashboard Time Limit Configuration (max days or overdue)
app.dashboard.max-time-limit-days=120


