-- =========================================================================
-- KRS Construction - Reorder Columns in krs_schema.projects Table (Zero Data Loss)
-- =========================================================================
-- This script re-arranges all 53 columns into a logical sequence without deleting
-- any existing project data or breaking foreign key references.
-- =========================================================================

BEGIN;

-- 1. Create temporary table with proper logical column sequence
CREATE TABLE krs_schema.projects_new (
    -- Identifiers
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sr_no BIGINT,
    notice_no VARCHAR(255),
    package_no VARCHAR(255),
    tender_id VARCHAR(255),

    -- Work & Department
    department_name VARCHAR(255),
    name_of_work TEXT,
    village_name VARCHAR(255),
    date_of_sub DATE,

    -- Contact & Reference
    related_to VARCHAR(255),
    ref_person VARCHAR(255),

    -- Financials & Costs
    tender_fee NUMERIC(19, 2),
    tender_fee_no VARCHAR(255),
    dd_no VARCHAR(255),
    emd_amt NUMERIC(19, 2),
    emd_no VARCHAR(255),
    estimated_tender_cost NUMERIC(19, 2),
    tendered_cost NUMERIC(19, 2),
    above_below_percentage NUMERIC(19, 2),

    -- Work Order & Timeline
    work_awarded_status VARCHAR(255),
    work_order_number VARCHAR(255),
    work_order_date DATE,
    time_limit VARCHAR(255),
    time_limit_extension DATE,
    completion_date_actual DATE,
    completion_date_extended DATE,

    -- Security Deposits & Deductions
    security_deposit_amount NUMERIC(19, 2),
    security_deposit_type VARCHAR(255),
    security_deposit_date DATE,
    sd_fdr_no VARCHAR(255),
    security_deposit_file VARCHAR(255),
    retention_money_per_bill NUMERIC(19, 2),
    extra_excess_amount NUMERIC(19, 2),
    sd_rab_deduction NUMERIC(19, 2),
    sd_rab_return_amount NUMERIC(19, 2),
    additional_deduction VARCHAR(255),

    -- Completion & Returns
    work_completed_amount NUMERIC(19, 2),
    pending_work_amount NUMERIC(19, 2),
    defects_liability_period VARCHAR(255),
    dlp_ended_on DATE,
    emd_return_status VARCHAR(255),
    sd_return_status VARCHAR(255),
    sd_rm_rab_return_status VARCHAR(255),
    status VARCHAR(255),

    -- Documents & Files
    letter_by_krs_file VARCHAR(255),
    letter_by_dept_file VARCHAR(255),
    negotiation_letter_file VARCHAR(255),

    -- Audit & Remarks
    remarks TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Copy all existing rows from old projects table to projects_new
INSERT INTO krs_schema.projects_new (
    id, sr_no, notice_no, package_no, tender_id,
    department_name, name_of_work, village_name, date_of_sub,
    related_to, ref_person,
    tender_fee, tender_fee_no, dd_no, emd_amt, emd_no, estimated_tender_cost, tendered_cost, above_below_percentage,
    work_awarded_status, work_order_number, work_order_date, time_limit, time_limit_extension, completion_date_actual, completion_date_extended,
    security_deposit_amount, security_deposit_type, security_deposit_date, sd_fdr_no, security_deposit_file, retention_money_per_bill, extra_excess_amount, sd_rab_deduction, sd_rab_return_amount, additional_deduction,
    work_completed_amount, pending_work_amount, defects_liability_period, dlp_ended_on, emd_return_status, sd_return_status, sd_rm_rab_return_status, status,
    letter_by_krs_file, letter_by_dept_file, negotiation_letter_file,
    remarks, is_active, created_by, updated_by, created_at, updated_at
)
SELECT 
    id, sr_no, notice_no, package_no, tender_id,
    department_name, name_of_work, village_name, date_of_sub,
    related_to, ref_person,
    tender_fee, tender_fee_no, dd_no, emd_amt, emd_no, estimated_tender_cost, tendered_cost, above_below_percentage,
    work_awarded_status, work_order_number, work_order_date, time_limit, time_limit_extension, completion_date_actual, completion_date_extended,
    security_deposit_amount, security_deposit_type, security_deposit_date, sd_fdr_no, security_deposit_file, retention_money_per_bill, extra_excess_amount, sd_rab_deduction, sd_rab_return_amount, additional_deduction,
    work_completed_amount, pending_work_amount, defects_liability_period, dlp_ended_on, emd_return_status, sd_return_status, sd_rm_rab_return_status, status,
    letter_by_krs_file, letter_by_dept_file, negotiation_letter_file,
    remarks, is_active, created_by, updated_by, created_at, updated_at
FROM krs_schema.projects;

-- 3. Drop old table CASCADE (temporarily removes foreign key constraints)
DROP TABLE krs_schema.projects CASCADE;

-- 4. Rename new table to projects
ALTER TABLE krs_schema.projects_new RENAME TO projects;

-- 5. Sync Identity Sequence to max ID
SELECT setval(
    pg_get_serialsequence('krs_schema.projects', 'id'),
    COALESCE((SELECT MAX(id) FROM krs_schema.projects), 1),
    true
);

-- 6. Restore Foreign Key constraints for child tables
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='krs_schema' AND table_name='project_locations') THEN
        ALTER TABLE krs_schema.project_locations 
        ADD CONSTRAINT fk_project_locations_project FOREIGN KEY (project_id) REFERENCES krs_schema.projects(id) ON DELETE CASCADE;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='krs_schema' AND table_name='ra_bills') THEN
        ALTER TABLE krs_schema.ra_bills 
        ADD CONSTRAINT fk_ra_bills_project FOREIGN KEY (project_id) REFERENCES krs_schema.projects(id) ON DELETE CASCADE;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='krs_schema' AND table_name='approvals') THEN
        ALTER TABLE krs_schema.approvals 
        ADD CONSTRAINT fk_approvals_project FOREIGN KEY (project_id) REFERENCES krs_schema.projects(id) ON DELETE CASCADE;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='krs_schema' AND table_name='project_documents') THEN
        ALTER TABLE krs_schema.project_documents 
        ADD CONSTRAINT fk_project_documents_project FOREIGN KEY (project_id) REFERENCES krs_schema.projects(id) ON DELETE CASCADE;
    END IF;
END $$;

COMMIT;
