-- =========================================================================
-- KRS Construction - Database Initialization Script
-- =========================================================================
-- NOTE: The actual tables are now managed dynamically by Liquibase in the backend!
-- This file is strictly for manual setup of the core database and user credentials
-- before running the backend application.
-- 
-- Execution Sequence:
-- =========================================================================

-- 1. Create the Database User (Secure Password)
CREATE USER krd_postgress WITH PASSWORD 'Krs@Prod!Db#2026';

-- 2. Create the Main Database
CREATE DATABASE krs_db WITH OWNER krd_postgress;

-- 3. Connect to the database (if using psql terminal, run: \c krs_db)
-- 4. Create a specific schema (Spring should be configured to use this instead of public)
CREATE SCHEMA IF NOT EXISTS krs_schema AUTHORIZATION krd_postgress;

-- 5. Grant absolute full permissions to the user on the database
GRANT ALL PRIVILEGES ON DATABASE krs_db TO krd_postgress;
GRANT ALL PRIVILEGES ON SCHEMA krs_schema TO krd_postgress;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA krs_schema TO krd_postgress;
ALTER DEFAULT PRIVILEGES IN SCHEMA krs_schema GRANT ALL ON TABLES TO krd_postgress;

-- 6. Create Liquibase Tables (Optional manual setup)
CREATE TABLE IF NOT EXISTS krs_schema.databasechangeloglock (
    id INT NOT NULL,
    locked BOOLEAN NOT NULL,
    lockgranted TIMESTAMP WITHOUT TIME ZONE,
    lockedby VARCHAR(255),
    CONSTRAINT pk_databasechangeloglock PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS krs_schema.databasechangelog (
    id VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    dateexecuted TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    orderexecuted INT NOT NULL,
    exectype VARCHAR(10) NOT NULL,
    md5sum VARCHAR(35),
    description VARCHAR(255),
    comments VARCHAR(255),
    tag VARCHAR(255),
    liquibase VARCHAR(20),
    contexts VARCHAR(255),
    labels VARCHAR(255),
    deployment_id VARCHAR(10)
);

-- Ensure permissions for the changelog tables
GRANT ALL PRIVILEGES ON TABLE krs_schema.databasechangeloglock TO krd_postgress;
GRANT ALL PRIVILEGES ON TABLE krs_schema.databasechangelog TO krd_postgress;

-- 7. Create Indexes for Liquibase tables (Optimizes Liquibase's search for executed changesets)
CREATE INDEX IF NOT EXISTS idx_databasechangelog_id_author_filename 
ON krs_schema.databasechangelog (id, author, filename);

-- =========================================================================
-- DEFAULT APPLICATION CREDENTIALS (Generated by Liquibase Migrations)
-- =========================================================================
-- Use these credentials to log into the Angular Frontend:
-- Username: YashModi1310Admin
-- Password: YaShAdmiN@1310
-- =========================================================================
